services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped

  app:
    build: .
    container_name: auth_service
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "
      until pg_isready -h db -U postgres; do
        echo waiting for database;
        sleep 2;
      done;
      PGPASSWORD=${DB_PASSWORD} psql -h db -U ${DB_USER} -d ${DB_NAME} -f /app/migrations/init.sql;
      go run cmd/main.go"

volumes:
  postgres_data:
